# Generated by Django 3.2.4 on 2021-07-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soft', '0003_auto_20210712_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='sharepoint',
            field=models.CharField(blank=True, max_length=80, verbose_name='sharepoint'),
        ),
        migrations.AlterField(
            model_name='level',
            name='number',
            field=models.IntegerField(verbose_name='number'),
        ),
    ]
